### PR TITLE
Add simulation.randomSource.

### LINKED ISSUE #121: Suggestion: add option for collide force to be deterministic
I'd like my force layout to produce the same results given the same inputs. However, since I'm using the collide force, this is not the case because the jiggle function uses Math.random. Can I suggest having the option to pass a  seed number to the collide force constructor, which can be used as a seed for a pseudo-random number generator instead of Math.random? Or possibly it could be an option which applies to the whole simulation, and then any forces that use a random number can use the same seeded pseudo-random number generator,  thus always producing the same layout given the same inputs.

### PR DESCRIPTION
**Pull request by mbostock**
Fixes #121.

~~TODO Default to a linear congruential generator rather than Math.random?~~ Done!

### CODE REVIEW

**Comment by Fil** [comment]
Would we add the lcg in d3-random then?

**Comment by mbostock** [comment]
We could, or we could do it here as the default value for simulation.randomSource.

**Comment by Fil** [comment]
I think it makes more sense in d3-random, but the code is so small it might be better to copy it here and avoid the additional dependency.

**Comment by mbostock** [comment]
I’ve added it to this PR.

**Comment by mcrawshaw** [comment]
Sorry to bug you, any chance we could get a minor release with this?

**Comment by Fil** [comment]
I initially planned to do a major release when #176 would be merged but it's a good idea to do a minor before in any case—so here is [v2.1.0](https://github.com/d3/d3-force/releases/tag/v2.1.0).

Note to self: In any event we'll release another version soon with larger dependencies (1—2).

**Pull request merged**
